# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          POSTGRES_PASSWORD: password
          PGPASSWORD: password
          PGPASS: password
          RAILS_ENV: test
      - image: circleci/postgres:12.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      # - run: rails test

      # Assets Build
      - run: npm install
      - run: npm run build

      # Snapshot Tests
      - run: curl https://chrissy-tuxedo-no2.s3.us-east-2.amazonaws.com/10-31-2020.dump -o latest.dump
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client-9.6
      - run: echo 'export PATH=/usr/lib/postgresql/12.1/bin/:$PATH' >> $BASH_ENV
      - run: ls -l /usr/local/lib/postgresql/
      - run: source ~/.bashrc
      - run: pg_restore --verbose --clean --no-acl --no-owner -h localhost -U postgres -d test latest.dump
      - run: rails server
      - run: npm run snapshots

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
